### ISSUE TITLE
scaleWidth not recognized in tween

### ISSUE THREAD

**Issue by Ovilia** [piqnt/stage.js#24]
I'm using `scaleWidth` instead of `scale` to make sure the texture is within 80% of the screen width and it works fine with the following setting.

```
node.pin({
  alignX: -0.5,
  alignY: -0.5,
  scaleMode: 'in',
  scaleWidth: window.innerWidth * 0.8,
  scaleHeight: window.innerHeight * 0.2,
});
```

But it seems that `scaleWidth` is not recognized by `tween` and it just gets ignored. So what should I do if I want to set `scaleWidth` in `tween`?

**Comment by vrbvillor** [comment]
It should be scaleX and scaleY, not the name you used

**Comment by shakiba** [comment]
scaleMode/Width/Height are not really pinning values, but they are compared with current width/height to calculate new scaleX/Y. Currently they are not supported by tween because implementing it is difficult, therefore you need to directly use scaleX/Y for tweening.

By the way, do not use `window` size, use `viewport` size instead (search docs for viewport).
